src/main/java/com/tenten/studybadge/common/exception/place/NotFoundPlaceException.java, src/main/java/com/tenten/studybadge/place/controller/PlaceController.java, src/main/java/com/tenten/studybadge/place/dto/PlaceCreateResponse.java, src/main/java/com/tenten/studybadge/place/service/PlaceService.java, src/test/java/com/tenten/studybadge/place/service/PlaceServiceTest.java
**AS-IS**
**TO-BE**
- 오프라인 일정 조회시 클라이언트 측에서 지도에 장소를 보여줄때 필요한 장소 정보 조회 api 구현
- 특정 studyChannel id와 연관관계는 없으며, 클라이언트 측에서 지도를 보여줄 때 필요한 장소 정보들을 db에 저장
- 만일 studyChannel이 방대해지고 장소를 저장하는 양이 많아지면 db 정리 필요 할듯하나 현재는 필요 없어서 따로 구현 안해놓은 상태입니다.
죄송합니다. 커밋 메시지 style이라고 해야하는데 Style로 잘못 썼으나 이미 push 해버려서 delete 없이 진행하겠습니다..
다음엔 소문자로 제대로 하겠습니다.
- service test코드만 진행
- controller test를  WebMvcTest으로 진행 했으나 현재 securiy적용되서 WithMockUser를 사용해도 에러가 나서 추후 추가할 예정.
=> feat: STD-15 장소 정보 조회

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/exception/participation/NotFoundParticipationException.java, src/main/java/com/tenten/studybadge/common/exception/participation/OtherMemberParticipationCancelException.java, src/main/java/com/tenten/studybadge/participation/controller/StudyChannelParticipationController.java, src/main/java/com/tenten/studybadge/participation/domain/entity/Participation.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java
**AS-IS** 
* 회원의 존재여부를 판단하지 않고 기능을 수행하도록 구현.
**TO-BE**
* 회원 기능이 개발되었기 때문에 회원 존재 여부를 판단하는 로직을 추가했습니다.
[추가된 기능]
* 스터디 채널에 참가 신청을 했던 걸 취소하는 기능을 구현했습니다.
* 참가 취소를 진행할 때 발생되는 예외 상황을 처리하도록 구현했습니다.
* 만약 다른 회원의 참가 신청을 취소하려고 할 경우 예외 발생(OtherMemberParticipationCancelException) 
* 존재하지 않는 참가 신청을 경우 예외 발생(NotFoundParticipationException)
- 컨트롤러 관련 테스트는 아직 구현하지 못했습니다.
=> feat: STD-13 스터디 채널 참가 신청 취소 기능

src/main/java/com/tenten/studybadge/schedule/controller/ScheduleController.java, src/main/java/com/tenten/studybadge/schedule/domain/Schedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/RepeatSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/SingleSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/RepeatScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/ScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/SingleScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
- scheduleService내에서 단일 일정 repository, 반복 일정 repository를 나름 DIP 원칙을 준수하고 싶어서 이렇게 구현했었습니다. 
``` java
@Service
@RequiredArgsConstructor
public class ScheduleService {
private final ScheduleRepository<SingleSchedule> singleScheduleRepository;
private final ScheduleRepository<RepeatSchedule> repeatScheduleRepository;
```
- RepeatSchedule, SingleSchedule에 기본 인덱스 외에는 인덱스를 설정하지 않았습니다.
- ScheduleRepository를 다음과 같이 설정해놨습니다.
``` java
public interface ScheduleRepository<T extends Schedule> {
T save(T entity);
}
```
``` java
@Repository
public interface RepeatScheduleRepository extends JpaRepository<RepeatSchedule, Long>,
ScheduleRepository<RepeatSchedule> {
}
```
``` java
@Repository
public interface SingleScheduleRepository extends JpaRepository<SingleSchedule, Long>, …
```
=> feat: STD-17 일정 조회

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/TokenConstant.java, src/main/java/com/tenten/studybadge/common/jwt/JwtTokenCreator.java, src/main/java/com/tenten/studybadge/common/token/controller/TokenController.java, src/main/java/com/tenten/studybadge/common/token/service/TokenService.java, src/main/java/com/tenten/studybadge/common/utils/CookieUtils.java, src/main/java/com/tenten/studybadge/member/controller/MemberController.java
**AS-IS**
반복적인 쿠키 관련 코드 CookieUtils로 분리 -> MemberController 쿠키관련 코드 수정
민호님이 충돌 해결 도중 SecurityConfig 코드내용 일부 삭제 되서 다시 추가했습니다.
**TO-BE**
- 토큰 재발급 추가
- 로그인 시 -> accessToken(헤더), refreshToken(쿠키)
- 만료되어 재발급 시 -> 새로운 accessToken(헤더) 
토큰에 대한 보안을 고려하여 수정하였습니다.
=> feat: STD-2 토큰 재발급, 쿠키 수정

src/main/java/com/tenten/studybadge/common/exception/schedule/OutRangeScheduleException.java, src/main/java/com/tenten/studybadge/schedule/controller/ScheduleController.java, src/main/java/com/tenten/studybadge/schedule/domain/Schedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/RepeatSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/SingleSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/RepeatScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/ScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/SingleScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/dto/RepeatScheduleCreateRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/RepeatScheduleEditRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/ScheduleCreateRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/ScheduleEditRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/ScheduleResponse.java, src/main/java/com/tenten/studybadge/schedule/dto/SingleScheduleCreateRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/SingleScheduleEditRequest.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
- 단일 일정, 반복 일정 테이블에 같은 인덱스명을 부과하였었습니다.
- 기존에는 아래와 같은 수정만 존재했었습니다. 
- 반복 일정 -> 반복 일정
- 단일 일정 -> 단일 일정
- 단일 일정 -> 반복 일정
**TO-BE**
- 단일 일정, 반복 일정 테이블에 다른 인덱스명으로 수정하였습니다.
- 반복 일정 -> 단일 일정 수정이 가능하도록 추가하였습니다.
- 반복 일정에서 단일 일정으로 수정할 경우 수정을 위해 날짜 선택하면(selectedDate) '이후 일정들도 동일하게 적용하겠습니까?'  라는 것에 O, X에 따라 수정하는 루트가 달라집니다.
- 기존 일정: 반복 일정 → 수정 요청: 단일 일정
- isAfterEventSame  = true : 이후 이벤트도 동일하게 수정 O
- isAfterEventSame  = false : 이후 이벤트도 동일하게 수정 X
ex > 2024.07.01(월) ~ 2024.07.15(월) 약 2주간 일정이 일간 매일 반복 일정일 때
- 선택한 수정 일정이 처음 날짜일 때 > selectedDate == scheduleDate
- [기존 반복 일정.scheduleDate += repeatCycle],  새로운 단일 일정 저장
- newSingleSchedule.scheduleDate == originRepeatSchedule.scheduleDate
- originRepeatSchedule.scheduleData += repeayCycle에 따른 plusMonth/Weeks/Day
- 선택한 수정 일정이 마지막 날짜일 때 > selectedDate …
=> feat: STD-18 일정 수정 (반 -> 단)

src/main/java/com/tenten/studybadge/common/exception/participation/NotAuthorizedRejectException.java, src/main/java/com/tenten/studybadge/participation/controller/StudyChannelParticipationController.java, src/main/java/com/tenten/studybadge/participation/domain/entity/Participation.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java
**AS-IS**
**TO-BE**
* 스터디 리더가 **참가 신청을 거절**하는 기능입니다.
* 참가 신청을 거절할 때 아래 조건을 만족하지 못하면 예외를 발생
* 만약 다른 스터디 채널의 참가 신청을 승인하려고 할 경우 예외가 발생
* 해당 스터디 채널의 리더가 아닌데 거절하려고 할 경우 예외가 발생
* 참가 신청 상태가 승인 대기중이 아닌 경우에는 예외가 발생
참가 신청을 거절할 경우 **참가 신청의 상태는 REJECTED**(거절됨) 이 됩니다.
=> feat: STD-14 참가 신청 거절 기능 

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/exception/studychannel/NotStudyLeaderException.java, src/main/java/com/tenten/studybadge/participation/ParticipantResponse.java, src/main/java/com/tenten/studybadge/participation/controller/StudyChannelParticipationController.java, src/main/java/com/tenten/studybadge/participation/domain/entity/Participation.java, src/main/java/com/tenten/studybadge/participation/domain/repository/ParticipationRepository.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
* 이전 기능(스터디 채널 생성, 참가 신청 관련 기능) 에서 내부적으로 memberId = 1L 같이 값을 만들어서 구현.
* 테스트 코드 내 특정 날짜를 지정
* SecurityConfig에 경로 설정할 때 저 상세한 주소가 뒤에 작성.
**TO-BE**
* Security 작업이 완료되어서 @AuthenticationPrincipal을 통해 memberId를 가져오도록 수정했습니다!
* 테스트 코드에서 특정 날짜를 기준으로 구현할 경우 테스트를 돌리는 날짜에 따라 오류가 발생했습니다. 따라서
현재 시간을 기준으로 plus 해서 날짜 관련 오류가 발생하지 않도록 했습니다.
* SecurityConfig에서 경로에 대한 허가 및 권한을 설정할 때 상세한 주소를 먼저 작성해야 해서 해당 부분을 수정
[구현한 기능]
* 특정 스터디 채널에 참가 신청을 한 참가 신청자들에 대한 조회 기능을 구현.
* 스터디 리더가 아닐 경우 신청자들을 조회할 수 없도록 했습니다.
=> feat: STD-21 스터디 참가 신청자 목록 조회 기능

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java, src/main/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannel.java, src/main/java/com/tenten/studybadge/study/channel/domain/repository/StudyChannelRepository.java, src/main/java/com/tenten/studybadge/study/channel/dto/StudyChannelDetailsResponse.java, src/main/java/com/tenten/studybadge/study/channel/service/StudyChannelService.java, src/main/java/com/tenten/studybadge/study/member/domain/entity/StudyMember.java, src/test/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannelTest.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
- 해당 스터디 채널의 리더인지 판단하는 로직이 stream의 filter와 map을 활용해 리더 여부를 반환하도록 구현되어 있었습니다.
**TO-BE**
- 멘토링 때 받은 피드백으로 anyMatch를 활용해서도 구현가능하다고 하셔서 anyMatch를 통해 동작하도록 리팩토링했습니다.
- 이를 위해 해당 엔티티에 대한 테스트 코드를 먼저 작성한 후 리팩토링을 진행했고 리팩토링 이후에서 테스트는 모두 정상입니다.
[기능 개발]
- 특정 스터디 채널 정보를 조회하는 기능을 구현
- 조회할 때 필요한 요구사항은 아래 3가지 입니다.
-  로그인한 회원이 아닐 경우 로그인을 해야한다.
- 해당 스터디 채널의 스터디 멤버가 아닐 경우 채팅 URL은 보이지 않아야 한다.
- 서브 리더가 없을 경우 서브 리더명에 현재 리더의 이름을 작성  
- 테스트 코드 작성 시 중복된 데이터가 많아서 이러한 데이터들은 테스트 클래스 내 인스턴스 변수로 지정해서 테스트를 진행
=> feat: STD-22 특정 스터디 채널 정보 조회 기능 구현

src/main/java/com/tenten/studybadge/common/exception/studychannel/AlreadyStudyMemberFullException.java, src/main/java/com/tenten/studybadge/common/exception/studychannel/NotChangeRecruitmentStatusException.java, src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java, src/main/java/com/tenten/studybadge/study/channel/domain/entity/Recruitment.java, src/main/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannel.java, src/main/java/com/tenten/studybadge/study/channel/service/StudyChannelService.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
**TO-BE**
스터디 채널 모집 시작 기능을 구현했습니다.
- 스터디 채널은 현재 상태가 "모집 마감" 상태일 때 가능합니다.
- 모집 시작 기능은 "리더"만 가능합니다.
- 만약 현재 스터디 멤버의 수와 정원 수가 동일할 경우 즉, 정원이 가득찼을 경우 예외가 발생합니다.
-  따라서 별도로 모집 인원을 늘려야 합니다.
=> feat: STD-23 스터디 모집 시작 기능 

src/main/java/com/tenten/studybadge/participation/controller/StudyChannelParticipationController.java, src/main/java/com/tenten/studybadge/participation/domain/entity/Participation.java, src/main/java/com/tenten/studybadge/participation/dto/ParticipantResponse.java, src/main/java/com/tenten/studybadge/participation/dto/StudyChannelParticipationStatusResponse.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java
**AS-IS**
- 모집 페이지에 보이는 참가자 목록 조회 기능을 구현 .
**TO-BE**
- 실제 모집 페이지에서는 현재 모집 상태에 따라 참가자 목록을 보여주거나 보여주지 않도록 되어야 합니다.
- 그래서 현재 스터디 채널의 모집 현황을 조회하는 API를 호출하면 아래와 같이 응답이 가도록 변경했습니다.
- "모집중" 일 경우
- 이때 현재 참가 신청자 목록과 현재 스터디 채널의 상태를 함께 반환
- "모집완료"일 경우
- 이때는 모집 상태만 반환하고 별도의 신청자 목록을 반환하지 않습니다.
모집완료 상태일 때 이미 해당 스터디 채널의 참가 신청 내역에는 "승인 대기" 상태인 데이터는 없어야하기 때문에
participationRepository에서 위와 같이 조회 쿼리를 날릴 수 있습니다.
하지만 모집완료인 상태에서는 별도의 조회 쿼리를 사용하지 않고 바로 빈 컬렉션을 반환해야 하기 때문에
이런 조회쿼리를 날리지 않도록 분기 처리를 했습니다.
```
// 1) 현재 모집 마감 상태일 경우
{
"studyChannelId" : 1,
"recruitmentStatus" : "RECRUITMENT_COMPLETED",
"participants" : {}
}
// 2) 모집중 상태일 경우
{
"studyChannelId" : 1,
"recruitment_status" : "RECRUITING",
"participants" : {
{
"memberId" : 참가 신청자 회원 아이디,
"participationId" : 참가 신청 아이디,
"badgeLevel" : 뱃지 레벨,
"profileImage" : …
```
=> feat: 참가 신청자 조회 기능에서 현재 스터디 채널의 참가 신청 상태를 조회하도록 변경

build.gradle, src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/Oauth2Contant.java, src/main/java/com/tenten/studybadge/common/constant/TokenConstant.java, src/main/java/com/tenten/studybadge/common/exception/oauth2/UnsupportedProviderException.java, src/main/java/com/tenten/studybadge/common/jwt/JwtTokenCreator.java, src/main/java/com/tenten/studybadge/common/oauth2/CustomOAuth2UserService.java, src/main/java/com/tenten/studybadge/common/oauth2/OAuth2SuccessHandler.java, src/main/java/com/tenten/studybadge/common/oauth2/OAuth2UserInfo.java, src/main/java/com/tenten/studybadge/common/security/CustomUserDetailService.java, src/main/java/com/tenten/studybadge/common/security/CustomUserDetails.java, src/main/java/com/tenten/studybadge/common/token/controller/TokenController.java, src/main/java/com/tenten/studybadge/common/token/dto/SocialLoginResponse.java, src/main/java/com/tenten/studybadge/common/token/dto/TokenCreateDto.java, src/main/java/com/tenten/studybadge/common/token/service/TokenService.java, src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/member/domain/entity/Member.java, src/main/java/com/tenten/studybadge/member/dto/MemberSignUpRequest.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java
**AS-IS**
- 기존 회원가입시 계좌번호만 존재하고 은행명 필드는 없었습니다.
- 기존 토큰 subject는 email로  설정되어있음 -> 이메일 중복 이슈로 id값으로 변경 할 예정입니다.
**TO-BE**
- OAuth2 로그인 구현
- Naver, Kakao 로그인
- 첫 로그인 시 자동 회원가입이 되며, 가입대기 상태로 가입 진행됩니다.
- 회원 가입이 되어 있으면, 바로 로그인 진행됩니다.
- 계좌나 자기소개 등은 추가 정보 입력 창으로 이동 -> 입력 후 활성 상태로 변경
- 은행명 필드 추가하였습니다.
- 이메일 중복 이슈로 인해 토큰 subject memberId로 변경했습니다.
- 이제 이메일이 아닌 memberId 로 멤버를 찾아옵니다.
- 프론트와 추가 상의 후 변경될 수도 있습니다.
=> feat: STD-6 OAuth2 로그인 구현

src/main/java/com/tenten/studybadge/common/exception/studychannel/NotStudyMemberException.java, src/main/java/com/tenten/studybadge/study/member/controller/StudyMemberController.java, src/main/java/com/tenten/studybadge/study/member/domain/entity/StudyMember.java, src/main/java/com/tenten/studybadge/study/member/domain/repository/StudyMemberRepository.java, src/main/java/com/tenten/studybadge/study/member/dto/StudyMemberInfoResponse.java, src/main/java/com/tenten/studybadge/study/member/dto/StudyMembersResponse.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java, src/test/java/com/tenten/studybadge/study/member/service/StudyMemberServiceTest.java
**AS-IS**
**TO-BE**
스터디 멤버 목록을 조회하는 기능을 구현했습니다.
- 현재 로그인한 회원이 해당 스터디 채널의 리더일 경우 isLeader 라는 플래그 값을 True로 반환합니다.
-  만약 리더가 아니고 스터디 멤버일 경우  isLeader 라는 플래그 값을 False로 반환합니다.
- 만약 해당 스터디 채널의 멤버가 아닐 경우 예외가 발생합니다.
=> feat: STD-25 스터디 멤버 목록 조회 기능 구현

src/main/java/com/tenten/studybadge/common/config/PaymentConfig.java, src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/exception/payment/InvalidAmountException.java, src/main/java/com/tenten/studybadge/payment/controller/PaymentController.java, src/main/java/com/tenten/studybadge/payment/domain/entity/Payment.java, src/main/java/com/tenten/studybadge/payment/domain/repository/PaymentRepository.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentRequest.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentResponse.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java, src/main/java/com/tenten/studybadge/type/payment/PayType.java, src/test/java/com/tenten/studybadge/payment/service/PaymentServiceTest.java
**AS-IS**
**TO-BE**
[구현 기능]
- 토스페이먼츠 API를 사용하여 결제 요청 기능을 구현하였습니다.
- 결제 요청 시 결제 모달 창이 뜨며, 본인의 스마트폰으로 결제 테스트 가능합니다.
***임시로 yml 파일에 성공/실패 Url 값을 넣어놨으며, 추후 프론트와 상의하여 변경할 예정입니다.***
**PaymentRequest에서 문자열은 따로 어디다 뺄지 애매하여 일단 두었습니다.**
**결제 명칭을 Payment로 할지 포인트 충전 개념인 Charge로 할지 고민중입니다.**
=> feat: STD-7 결제요청 구현

src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java, src/main/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannel.java, src/main/java/com/tenten/studybadge/study/channel/dto/StudyChannelEditRequest.java, src/main/java/com/tenten/studybadge/study/channel/service/StudyChannelService.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
**TO-BE**
- 스터디 채널 정보를 수정하는 기능을 구현했습니다.
- 일단 프론트 측에서 수정할 데이터 중 변경된 값과 기존 값을 모두 같이 보내준다는 가정하에 코드를 작성했습니다.
- 스터디 리더가 아닐 경우 스터디 채널 정보를 수정할 수 없습니다.
=> feat: STD-26 스터디 채널 정보 수정 기능 구현

build.gradle, src/main/java/com/tenten/studybadge/common/config/WebClientConfig.java, src/main/java/com/tenten/studybadge/common/constant/PaymentConstant.java, src/main/java/com/tenten/studybadge/common/exception/payment/AlreadyApprovedException.java, src/main/java/com/tenten/studybadge/common/exception/payment/AlreadyApprovedPaymentException.java, src/main/java/com/tenten/studybadge/common/exception/payment/NotFoundOrderException.java, src/main/java/com/tenten/studybadge/common/exception/payment/NotMatchAmountException.java, src/main/java/com/tenten/studybadge/payment/controller/PaymentController.java, src/main/java/com/tenten/studybadge/payment/domain/repository/PaymentRepository.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentConfirm.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentConfirmRequest.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java
**AS-IS**
**TO-BE**
[기능 구현]
- 토스페이먼츠 결제 승인 요청하는 기능을 구현하였습니다.
- 승인이 성공적으로 완료되면, 토스 테스트서버에 결제내역에 결제완료로 남게됩니다.
- paymentKey는 토스 결제 식별키로 데이터베이스에 저장됩니다.
- 결제 성공 후 successYN이 기존 false에서 true를 반환하게 됩니다.
**브랜치 이름은 success이지만 어감이 이상하여, confirm으로 변경된 점 이해해주시길 바랍니다.**
***간단하게 RestTemplate을 사용하려했지만, Spring 에서 Webclient를 권장하여 Webclient를 적용하였습니다.***
Webclient를 더 알아보고 더 깔끔하게 작성할 수 있게 추후에 리팩토링도 진행할 예정입니다.
=> Feat: STD-8 결제 승인(성공) 기능 구현

src/main/java/com/tenten/studybadge/common/exception/studychannel/AlreadyExistsSubLeaderException.java, src/main/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannel.java, src/main/java/com/tenten/studybadge/study/member/controller/StudyMemberController.java, src/main/java/com/tenten/studybadge/study/member/domain/entity/StudyMember.java, src/main/java/com/tenten/studybadge/study/member/dto/AssignRoleRequest.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java, src/test/java/com/tenten/studybadge/study/member/service/StudyMemberServiceTest.java
**AS-IS**
- StudyChannel 내 getLeader, getSubLeader 메서드가 private 으로 선언.
**TO-BE**
- getLeader, getSubLeader 메서드의 접근 제어자를 public으로 수정
[기능]
- 리더가 특정 스터디 멤버에게 서브 리더 역할을 부여하는 기능을 구현.
- 스터디 채널 당 1명의 서브 리더를 부여할 수 있습니다.
- 따라서 스터디 채널 내 서브 리더의 역할을 가진 스터디 멤버가 존재할 경우 예외가 발생합니다.
[문제 해결]
- AssignRoleRequest와 같이 하나의 값만 갖고 있는 DTO를  Object로 변환할 때 기본 생성자가 없을 경우 예외가 발생.
- 관련 이슈 : https://github.com/FasterXML/jackson-databind/issues/3085
=> feat: STD-27 서브 리더 역할 부여 기능

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/PaymentConstant.java, src/main/java/com/tenten/studybadge/common/exception/payment/NotEnoughPointException.java, src/main/java/com/tenten/studybadge/payment/controller/PaymentController.java, src/main/java/com/tenten/studybadge/payment/domain/repository/PaymentRepository.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentCancelRequest.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentConfirm.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java
**AS-IS**
- 결제 재 테스트 시 오류가 발생하여 확인했더니, requestedAt, approvedAt를 LocalDateTime으로 바꾼게 문제였습니다.
- 토스 측에서 LocalDateTime 값이 아닌 String 값으로 정한 것을 잊고 피드백을 반영하고 바꿨었습니다.
- 서비스와 컨트롤러 메서드의 이름이 부자연스러운 상태였습니다.
**TO-BE**
- 결제 취소 기능을 추가했습니다.
- 결제 취소 시 토스 측에서 스마트폰으로 알림이 오는 것을 확인할 수 있습니다.
- ~At 값들을 토스 측 요구에 맞게 String으로 다시 바꾸었습니다.
- 서비스와 컨트롤러 메서드의 명을 자연스럽게 변경하였습니다
- Dto 명은 네이밍규칙에 맞게 유지하기로 했습니다.
***포인트 테이블이 추가로 생기면 변경사항이 있을 수 있습니다***
=> Feat: STD-29 결제 취소 기능 구현

src/main/java/com/tenten/studybadge/attendance/controller/AttendanceController.java, src/main/java/com/tenten/studybadge/attendance/domain/entity/Attendance.java, src/main/java/com/tenten/studybadge/attendance/domain/repository/AttendanceRepository.java, src/main/java/com/tenten/studybadge/attendance/dto/AttendanceCheckRequest.java, src/main/java/com/tenten/studybadge/attendance/dto/AttendanceMember.java, src/main/java/com/tenten/studybadge/attendance/service/AttendanceService.java, src/main/java/com/tenten/studybadge/common/exception/attendance/InvalidAttendanceCheckDateException.java, src/main/java/com/tenten/studybadge/type/attendance/AttendanceStatus.java, src/test/java/com/tenten/studybadge/attendance/service/AttendanceServiceTest.java
**AS-IS**
**TO-BE**
- 출석 체크 기능은 일정 당일에만 동작할 수 있도록 했습니다.
- 출석 체크 기능은 아래와 같이 2가지 기능이 있습니다.
- 처음 출석 체크를 할 경우 프론트 쪽에서 스터디 멤버들의 출석 체크 정보를 한 번에 보냅니다. 따라서 첫 출석 체크일 경우 모든 스터디 멤버의 출석 정보를 한 번에 저장됩니다.
- 이후 출석 상태를 변경(출석 취소 or 출석 체크)하게 될 경우 변경된 정보를 보내면 변경된 스터디 멤버의 출석 상태들을 반영하도록 했습니다.
예) 첫 출석 체크 - 스터디 멤버가 3명이라고 가정
```json
{
attendanceMembers : [
{
"studyMemberId" : 11,
"isAttendance" : true
},
{
"studyMemberId" : 12,
"isAttendance" : false
},
{
"studyMemberId" : 13,
"isAttendance" : true
}
]
}
``` 
위와 같은 요청이 오면 백엔드에서는 존재하지 않는 출석 체크일 경우 출석 내역을 저장합니다.
예) 수정 할 때
```json
{
attendanceMembers : [
{
"studyMemberId" : 12,
"isAttendance" : true
},
]
}
``` 
위와 같은 요청이 왔을 때 존재하는 출석 체크일 경우 해당 멤버의 출석 상태를 변경합니다.
[문제 해결]
- AttendanceMember 클래스 내부에 @Getter와 boolean의 변수명이 isAttendance로 되어 있습니다.
- 이때 변수명이 is_ 로 되어 있고 …
=> feat: STD-31 출석 체크 기능

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/config/WebMvcConfig.java, src/main/java/com/tenten/studybadge/common/constant/Oauth2Contant.java, src/main/java/com/tenten/studybadge/common/oauth2/OAuth2FailureHandler.java, src/main/java/com/tenten/studybadge/common/security/CustomAuthenticationEntryPoint.java, src/main/java/com/tenten/studybadge/common/security/LoginUser.java, src/main/java/com/tenten/studybadge/common/security/LoginUserArgumentResolver.java, src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/payment/controller/PaymentController.java
**AS-IS**
- 컨트롤러에서 `@AuthenticationPrincipal principal` -> `(principal.getId)` 로 memberId를 가져왔었습니다. 
- 토큰을 넣지 않거나 유효하지 않은 토큰을 헤더에 넣어 API 호출했을 때, Oauth2 기본 로그인 페이지가 응답했었습니다.
- Oauth2 실패 핸들러가 구현되지 않았었습니다.
**TO-BE**
- 멘토링 피드백을 반영하여 커스텀 어노테이션을 만들었습니다. **이 방식이 맞는지는 잘 모르겠습니다만**, 컨트롤러 역할 분리와
'아주 아주' 약간 편리해졌다는 점이 있는 것 같습니다. ( 멘토님이 말씀하신건, 제가 찾아본 바로는 stateful 서버에서 세션에서 유저정보를 인터셉트 하여 커스텀 어노테이션을 만들어서  memberId를 받아오는 걸로 생각하고 있습니다. 
(**제 생각이 맞다는게 아닙니다^^** )
- 컨트롤러에서 `@LoginUser Long memberId` -> `(memberId)` 로 memberId를 받아오시면 되겠습니다.
- 혹여나 `-parameter` 에러 발생 시 인텔리제이 설정에서 빌드를 IntelliJ에서 Gradle로 변경해주시면 됩니다.
- 토큰을 넣지 않거나 유효하지 않은 토큰을 헤더에 넣어 API 호출했을 때, 401에러가 발생하도록 핸들러를 추가하였습니다.
- Oauth2 실패 핸들러를 추가하였습니다 -> 인증 실패시 현재는 임시로 "/login" 으로 이동하게 설정해놓았습니다.
***커스텀 어노테이션 적용함에 따라, 추가 커밋으로 그에 맞게 컨트롤러가 변경될 예정입니다.***
=> Refactor: STD-6 커스텀 어노테이션, 핸들러 추가

src/main/java/com/tenten/studybadge/attendance/controller/AttendanceController.java, src/main/java/com/tenten/studybadge/attendance/domain/repository/AttendanceRepository.java, src/main/java/com/tenten/studybadge/attendance/dto/AttendanceInfoResponse.java, src/main/java/com/tenten/studybadge/attendance/service/AttendanceService.java
**AS-IS**
**TO-BE**
- 스터디 채널 내 스터디 멤버별 출석 현황(출석률, 멤버명, 이미지)를 조회하는 기능입니다.
- 출석률을 계산하는 방법
-  전체 일정의 총 일수(단일 일정의 경우 단일 일정 당 1일, 반복 일정의 경우 반복 주기를 통해 계산)
- 단일 일정 : 단일 일정이 2개 있을 경우 단일 일정의 총 일수는 2일입니다.
- 반복 일정 : 반복 주기가 "주" 일 경우 시작 날짜부터 종료날짜까지 "주" 단위로 몇 번 반복하는지 카운트
-  각 일정 별 스터디 멤버들의 출석 상태가 "출석(ATTENDANCE)" 일 경우에만 출석한 날로 인정됩니다.
현재는 좀 복잡하게 애플리케이션 내부에서 필터링과 카운팅을 하고 있습니다.
하나의 일정에 대한 스터디 멤버들의 출석 일수를 구하는 쿼리를 직접 작성해서 native query로 할지
이대로 진행할 지 고민중입니다.
=> feat: STD-32 스터디 채널 내 출석 현황 조회 기능

src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/member/dto/MemberStudyList.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java, src/main/java/com/tenten/studybadge/payment/controller/PaymentController.java, src/main/java/com/tenten/studybadge/study/member/domain/repository/StudyMemberRepository.java
**AS-IS**
-회원 정보 수정과 회원 탈퇴에 스웨거 작성이 되지 않았었습니다.
-불필요한 import 가 있었습니다.
**TO-BE**
- 회원이 참여중인 스터디 목록을 조회할 수 있는 기능을 추가했습니다.
- 조회 시 참여중인 스터디 이름과, 역할을 볼 수 있습니다. 
- `[
{
"studyId": 1,
"studyName": "모각코",
"role": "STUDY_MEMBER"
}
]`
- 정보 수정과 회원 탈퇴에 스웨거 작성하였습니다.
- 불필요한 import 제거했습니다.
=> Feat: STD-4 회원 스터디 참여 목록 조회

src/main/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannel.java, src/main/java/com/tenten/studybadge/study/channel/dto/StudyChannelDetailsResponse.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
* 특정 스터디 채널조회 시 리더인지 여부를 판단할 수 있는 값이 존재하지 않음.
**TO-BE**
* 특정 스터디 채널 조회 시 리더인지 여부를 판단할 수 있는 값을 추가
* isLeader() 에서 member 가 null 일 경우 false로 반환하도록 코드 추가
=> feat: 특정 스터디 채널 조회 시 리더 여부에 대한 정보 추가

src/main/java/com/tenten/studybadge/attendance/domain/entity/Attendance.java, src/main/java/com/tenten/studybadge/study/member/controller/StudyMemberController.java, src/main/java/com/tenten/studybadge/study/member/dto/ScheduleStudyMemberResponse.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java
**AS-IS**
**TO-BE**
특정 일정에서의 스터디 멤버 목록을 조회하는 기능입니다.
조회할 때 다음과 같은 요구사항이 있습니다.
* 오늘을 기준으로 이전 날짜에 대한 일정(출석이 완료된)의 경우 회원 정보와 출석 정보를 함께 전송한다.
* 오늘을 기준으로 이후 날짜에 대한 일정(출석이 되지 않은)의 경우 회원 정보만 조회.
단일 일정의 경우 해당 단일 일정 ID 만으로 출석 여부나 이전 날짜인지를 판단할 수 있습니다.
하지만 반복 일정의 경우 반복 일정 ID가 있더라도 반복 일정 내 특정 날짜를 기준으로 출석을 하기 때문에 일정 날짜를 파라미터로 함께 보내도록 했습니다.
예) 반복 일정 : 2024-07-01 ~ 2024-07-29 일 경우
- 오늘 : 2024-07-10 이라고 가정
-   07-01 일정에서의 스터디 멤버 정보를 조회할 경우 이미 출석 체크된 지난 일정이기 때문에 출석 정보를 함께 조회
-   07-15 일정에서의 스터디 멤버 정보를 조회할 경우 아직 출석 체크되지 않은 일정이기 때문에 스터디 멤버 정보만 조회
[예시 응답]
**이미 지난(출석 체크된) 일정의 경우**
```json
{
"memberId" : "회원 ID",
"studyMemberId" : "스터디 멤버 ID",
"name" : "이름",
"imageUrl" : "이미지 경로",
"attendance_status" : "ATTENDANCE" 또는 "ABSENCE",
"isAttendance" : true 또는 false
}
, 
// ...
```
**아직 지나지 않은(출석 체크하지 않은)일정의 경우** …
=> feat: STD-33 특정 일정의 스터디 멤버 목록 조회 기능

src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/study/deposit/domain/entity/StudyChannelDeposit.java, src/main/java/com/tenten/studybadge/study/deposit/domain/repository/StudyChannelDepositRepository.java, src/main/java/com/tenten/studybadge/type/study/deposit/DepositStatus.java, src/main/java/com/tenten/studybadge/type/study/member/StudyMemberStatus.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java
**AS-IS**
- 기존 참가 신청 승인 로직의 경우 참가 신청 내역의 상태를 "승인" 상태로 변경 후 스터디 멤버에 등록하는 2개의 과정만 존재.
- 참가 신청 승인 기능의 경우 @Transactional이 붙어져 있었다.
**TO-BE**
- @Transactional 제거
- 스터디 채널에 스터디 채널 예치금 내역(**StudyChannelDeposit**) 이라는 엔티티를 설계
-  예치금 내역의 경우 해당 스터디 채널 내에 현재 어떤 회원이 얼마의 예치금을 넣어놨는지 기록
- 그리고 추후 출석률에 따른 환급 금액을 계산하거나, 퇴출, 나가기를 했을 때 예치금을 관리하는 목적
**[최종 참가 신청 승인 시나리오]**
-  (기존) 참가 신청 내역을 "승인" 상태로 변경
- (기존) 스터디 채널 멤버로 등록
- (**추가**) **포인트 내역 기록** 
- (**추가**) **회원 보유 포인트 차감**
- (**추가**) **스터디 채널 예치금 내역 기록**
[고민인 부분]
현재 위 단계에서 트랜잭션의 범위를 어떻게 나눠야하는지 고민중입니다.
- 참가 신청 승인 테스트 내에 추가된 테스트
- 1. 스터디 멤버로 등록되었는가
- 2. 포인트 내역이 기록되었는가
- 3. 회원의 보유 포인트가 차감되었는가
- 4. 스터디 채널 예치금 내역이 기록되었는가
=> feat: STD-35 참가 신청 승인 기능에 포인트 및 예치금 관련 기능 추가

src/main/java/com/tenten/studybadge/common/config/CorsConfig.java, src/main/java/com/tenten/studybadge/common/config/RedisConfig.java, src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/NotificationConstant.java, src/main/java/com/tenten/studybadge/common/exception/notification/NotificationContentEmptyException.java, src/main/java/com/tenten/studybadge/common/exception/notification/NotificationContentLengthOverException.java, src/main/java/com/tenten/studybadge/common/redis/RedisPublisher.java, src/main/java/com/tenten/studybadge/common/redis/RedisSubscriber.java, src/main/java/com/tenten/studybadge/notification/controller/NotificationController.java, src/main/java/com/tenten/studybadge/notification/domain/NotificationContent.java, src/main/java/com/tenten/studybadge/notification/domain/RelatedUrl.java, src/main/java/com/tenten/studybadge/notification/domain/entitiy/Notification.java, src/main/java/com/tenten/studybadge/notification/domain/repository/EmitterRepository.java, src/main/java/com/tenten/studybadge/notification/domain/repository/EmitterRepositoryImpl.java, src/main/java/com/tenten/studybadge/notification/domain/repository/NotificationRepository.java, src/main/java/com/tenten/studybadge/notification/dto/DummyData.java, src/main/java/com/tenten/studybadge/notification/dto/NotificationResponse.java, src/main/java/com/tenten/studybadge/notification/service/NotificationService.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/main/java/com/tenten/studybadge/type/notification/NotificationType.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
**TO-BE**
- 하트 비트 없이 클라이언트와 서버의 연결 time out 시간을 2분으로 설정했습니다.
- 클라이언트와 서버의 연결이 자꾸 끊기고 알 수 없는 (501 에러, 서버에서 close 된 에러 X) 에러로 인해 하트비트를 설정했으나 연결이 끊기는 것은 마찬가지여서 삭제하고 2분으로 늘렸습니다. 혹시라도 sse에 대해 제가 잘못 구현한 부분이 있으면 언제든지 말씀해주세요. 
- sse 알림 부분이 미숙해 시간이 너무 오래 지나 일단 서버 연동이 멀티 WAS가 아님에도 redis pub/sub을 적용해놨습니다.
- 이 부분은 오버 엔지니어링이 될 수 있음을 인정합니다. 
- 일정 등록/수정/삭제 시에 해당 스터디 채널 멤버의 실시간 알림이 가는 것을 확인했습니다.
- 만일 해당 스터디 채널의 멤버가 아니면 알림이 생성되더라도 알림이 안 가는 것을 확인했습니다.
- 프론트의 요구로 더미데이터를 isDummy true로 주기 위해 클래스를 새로 만들었습니다. (연결 후 아무것도 전송하지 않으면 503에러 발생때문) 
**TO-DO**
- 관련 url은 추후 클라이언트의 api 경로로 수정해야합니다.
- 클라이언트에서 클릭할 때의 기능이 구현되면 그때 수정하겠습니다.
- 현재 로그인 후 access token이 알림 세션 연결때는 이어지지 않아 따로 token 값을 넣어주면서 확인했습니다. 그래서 다른 브라우저에서의 알림 비교를 하지 못했습니다. 해당 부분은 이어지면 다시 확인하도록 하겠습니다. 
- 다음과 같은 api 기능이 추가 될 예정입니다.
- 전체 알림 List를 get
- …
=> feat: STD-20 알림 기능 

src/main/java/com/tenten/studybadge/common/exception/studychannel/LeaveStudyLeaderException.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/study/deposit/domain/entity/StudyChannelDeposit.java, src/main/java/com/tenten/studybadge/study/member/controller/StudyMemberController.java, src/main/java/com/tenten/studybadge/study/member/domain/entity/StudyMember.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java
**AS-IS**
- 스터디 채널 예치금 엔티티에 스터디 멤버 상태가 존재
**TO-BE**
- 스터디 채널 예치금 엔티티에 스터디 멤버 상태 제거
- 스터디 멤버에 스터디 멤버 상태 추가
[스터디 채널 나가기]
- 스터디 채널을 나갈 때 리더의 경우 나갈 수 없도록 했습니다.
- SOFT DELETE를 위해 @SqlDelete 적용
=> feat: STD-38 스터디 채널 나가기 기능

src/main/java/com/tenten/studybadge/StudyBadgeApplication.java, src/main/java/com/tenten/studybadge/common/config/JpaConfig.java, src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/notification/controller/NotificationController.java, src/main/java/com/tenten/studybadge/notification/domain/repository/NotificationRepository.java, src/main/java/com/tenten/studybadge/notification/service/NotificationService.java, src/test/java/com/tenten/studybadge/notification/controller/NotificationControllerTest.java, src/test/java/com/tenten/studybadge/notification/service/NotificationServiceTest.java
**AS-IS**
- SpringBootApplication 위에 EnableJpaAuditing 어노테이션 존재
**TO-BE**
- 알림 전체 조회 기능 구현
- Jpa 관련 JpaConfig 설정 클래스로 분리해 해당 클래스에 EnableJpaAuditing 어노테이션 존재 
- controller test:  WebMvcTest할 때는 Service, Repository, Component 등은 빈으로 등록하지 않는데 main에 EnableJpaAuditing이 있으면 JPA 관련 빈을 찾으려 하기 때문에 에러가 남
=> feat: STD-40 알림 전체 조회 기능

src/main/java/com/tenten/studybadge/schedule/controller/ScheduleController.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
- AuthenticationPrincipal 어노테이션으로 token으로 memberDetail을 가져와 검증했습니다.
- 반복 일정에서 단일 일정으로 수정할 때 새로운 단일 일정으로 생성하는 과정에서 중복 메서드가 존재했습니다.
**TO-BE**
- 전반적으로 줄바꿈을 +1해 적은 화면으로도 매개변수를 쉽게 볼 수 있도록 수정했습니다.
- LoginUser 커스텀 어노테이션으로 변경하였습니다.
- 새로운 단일 일정으로 생성하는데 중복 메서드를 1개의 메서드로 적용했습니다.
- 이전에 api 테스트와(postman), 테스트 코드시에 memberId와 studyChannelId가 모두 1L으로 동일해서 잘못된 점을 인지하지 못했으나 코드를 살펴보던 중 매개변수의 순서가 잘못된 것을 알고 고쳐 fix 커밋 해두었습니다.
=> refactor: 전반적인 일정 코드 리팩토링

build.gradle, src/main/java/com/tenten/studybadge/common/config/QuartzConfig.java, src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/NotificationConstant.java, src/main/java/com/tenten/studybadge/common/quartz/AutowiringSpringBeanJobFactory.java, src/main/java/com/tenten/studybadge/common/quartz/RepeatScheduleNotificationJob.java, src/main/java/com/tenten/studybadge/common/quartz/SchedulerJobListener.java, src/main/java/com/tenten/studybadge/common/quartz/SingleScheduleNotificationJob.java, src/main/java/com/tenten/studybadge/notification/service/NotificationSchedulerService.java, src/main/java/com/tenten/studybadge/notification/service/NotificationService.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/main/java/com/tenten/studybadge/type/notification/NotificationType.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
- 알림 타입이 TEN_MINUTES_BEFORE_ATTENDANCE로 길더라도 의미 전달을 최우선으로 했습니다.
- scheduleServcie에서 반복 일정의 시작날짜와 끝나는 날짜를 변경할 때 사용하는 메서드를 void 형으로 두었습니다.
- SecurityConfig에 단일 일정, 반복 일정 생성 및 자세히 조회하는 경로를 명시적으로 적지 않았습니다.
**TO-BE**
- 알림 타입을 SCHEDULE_REMINDER으로 수정하여 CREATE, DELETE 등 일관성을 최우선으로 했습니다.
- scheduleServcie에서 반복 일정의 시작날짜와 끝나는 날짜를 변경할 때 사용하는 메서드를 save한 것을 return하도록 변경하였습니다.
- reScheduling 시 기존 일정/ 새로 업데이트한 일정을 매개변수로 넣기 위함
- SecurityConfig에 단일 일정, 반복 일정 생성 및 자세히 조회하는 경로를 명시적으로 적었습니다.
- 스케줄링을 위해 Quartz을 사용했습니다. 
- 매일 특정 시간에(Scheduled 어노테이션) db를 조회하여 오늘 존재하는 일정들을 찾는 것은 서버에 의도치않은 부하나 비효율적이라고 생각됐고,일정이 등록되고 수정되고 삭제될때 스케줄링을 등록하는 Quartz가 적당하다고 생각했습니다.
**- 출석 체크 알림이 스케줄링 되는 과정은 다음과 같습니다.**
- 일정 등록: scheduling 메서드 [trigger, Job detail 등록]
- 단일 일정> simple trigger로 job detail  등록
- 반복 일정> cron trigger로 …
=> feat: STD-20 알림 기능: 일정의 출석체크 하기 10분전 스터디 멤버에게 알림 전송

src/main/java/com/tenten/studybadge/attendance/service/AttendanceService.java, src/main/java/com/tenten/studybadge/common/exception/schedule/NotIncludedInRepeatScheduleException.java, src/main/java/com/tenten/studybadge/common/jsondeserializer/ScheduleEditRequestDeserializer.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
- 반복 일정에 속하지 않은 날짜일 경우 보내는 exception 명: OutRangeScheduleException으로 두었었음
- 반복 일정을 수정/삭제할 때 repeatSchedule에 속한 일정이 아닌 것을 단순히 Daily 반복 일정으로만 생각해 첫날/ 마지막날만 체크했음
-  현재 날짜보다 지난 날짜를 선택했을 경우 exception을 주어야하는 것에 기존 반복 일정의 첫날로 확인해 삭제할 수 있음에도 삭제가 불가했음
- 이전에 memberId 필드를 추가했을 때 json 역직렬화에도 추가를 하지 않아 memberId를 읽지 못하는 에러가 존재했음
**TO-BE**
- 반복 일정에 속하지 않은 날짜일 경우 보내는 exception 명: NotIncludedInRepeatScheduleException으로 수정함
- 반복 일정을 수정/삭제할 때 주간/월간에도 맞게 확인함
- 현재 날짜보다 지난 날짜를 선택했을 경우 exception을 제대로 주고 삭제할 수 있는 날짜를 선택했을 경우 삭제가 가능함
- json 역직렬화에 memberId를 추가해 제대로 역직렬화를 하여 에러가 없음.
=> fix: STD-18, STD-19 반복 일정 수정/ 삭제시 날짜 유효성 검증 잘못되었던 것 수정

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/MailConstant.java, src/main/java/com/tenten/studybadge/common/constant/Oauth2Contant.java, src/main/java/com/tenten/studybadge/common/email/MailService.java, src/main/java/com/tenten/studybadge/common/exception/member/NotAuthorizedPasswordAuth.java, src/main/java/com/tenten/studybadge/common/jwt/JwtTokenCreator.java, src/main/java/com/tenten/studybadge/common/oauth2/OAuth2SuccessHandler.java, src/main/java/com/tenten/studybadge/common/oauth2/OAuth2UserInfo.java, src/main/java/com/tenten/studybadge/common/security/CustomUserDetails.java, src/main/java/com/tenten/studybadge/common/token/dto/TokenCreateDto.java, src/main/java/com/tenten/studybadge/common/token/service/TokenService.java, src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/member/domain/entity/Member.java, src/main/java/com/tenten/studybadge/member/domain/type/MemberRole.java, src/main/java/com/tenten/studybadge/member/dto/MemberSignUpRequest.java, src/main/java/com/tenten/studybadge/member/dto/MemberUpdateRequest.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java, src/main/java/com/tenten/studybadge/type/member/MemberRole.java, src/test/java/com/tenten/studybadge/notification/controller/NotificationControllerTest.java, src/test/java/com/tenten/studybadge/notification/service/NotificationServiceTest.java
**AS-IS**
- Oauth2 인증 완료 후 RedirectUrl이 프론트 측과 맞지 않게 설정되어 있었습니다.
- MemberUpdateRequest 에 은행명이 없었습니다.
- 결제내역 조회 서비스 코드 중 page -1을 추가하지 않았었습니다.
- member/type 에 MemberRole이 위치해있었습니다.
**TO-BE**
- 비밀번호 재설정 기능을 추가하였습니다.
- 로컬 회원이 비밀번호를 잊은 경우 비밀번호 재설정을 통해 해결할 수 있습니다.
- `비밀번호 재설정 흐름 : 재설정 요청 -> 이메일 전송 -> 링크 접속 -> 코드 인증 -> 비밀번호 재설정`
-  Oauth2 인증 완료 후 RedirectUrl이 프론트 측과 상의하여 수정하였습니다.
- MemberUpdateRequest 에 은행명 필드를 추가하였습니다.
- 1페이지부터 조회가능 하도록 결제내역 조회 서비스 코드 중 page -1을 추가였습니다.
- MemberRole을 type/member로 위치하게하였습니다.
=> feat: STD-43 비밀번호 재설정 기능 추가

src/main/java/com/tenten/studybadge/notification/service/NotificationSchedulerService.java, src/test/java/com/tenten/studybadge/notification/service/NotificationSchedulerServiceTest.java
**AS-IS**
- 반복 일정의 trigger가 startAt과 endAt을 두지 않아 무한으로 cron 주기에 맞게 알림이 전송되었었음(해당 일정이 없음에도 출석체크하라는 알림)
- 알림 체크를 확인하기 위해 일부러 이전 날짜로 등록했을 때도 출석 체크 알림이 동일하게 왔었음
- misfire가 존재할 때 바로 실행하도록 설정해두었기 때문 
**TO-BE**
- 반복 일정에 startAt, endAt을 두었음
- 단일 일정에도 명시적으로 startAt, endAt을 해당 날짜로 두었음
- 단일 일정: 현재 날짜보다 일정 시작 날짜가 지난 날짜면 trigger, job detail을 등록하지 않도록 if문 추가
- 반복 일정: 현재 날짜보다 일정 끝나는 날짜가 지난 날짜면 trigger, job detail을 등록하지 않도록 if문 추가
- 알림 체크를 확인하기 위해 일부러 이전 날짜로 등록했을 때도 출석 체크 알림이 오지 않음
- misfire(전송이 안된 trigger, 등)가 존재할 때 무시하고 다음 trigger 일정을 그대로 유지하도록 변경
- 이것은 만약 출석 체크 알림이 전송 안되는 경우에 다시 전송되지 않도록 설정한 것
- 추후 크리티컬한 부분이면 설정을 다시 변경해두겠습니다. 그러나 지금은 크리티컬하지 않다고 생각되어 무시하고 다음 trigger 설정을 따르도록 해놨습니다.
***TO-DO***
***현재 misfire문제로 제가 착각하고있었던 오류는 해결된 상황이긴 합니다!
그러나 조금 더 확실한 확인을 위해 배포서버에서 확인해야 하는 부분은 다음과 같습니다.***
- 배포된 서버에서 …
=> fix: STD-20 출석 체크 알림 스케줄링 시 trigger 문제 수정

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/participation/domain/repository/ParticipationRepository.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/SingleSchedule.java, src/main/java/com/tenten/studybadge/study/member/domain/repository/StudyMemberRepository.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java
**AS-IS**
- 스터디 채널 조회 시 studyChannelRepository.findById(studyChannelId)로 조회한 후 내부에 OneToMany로 되어있는 studyMembers로 접근
- 참가 신청 내역 조회 시 findById()로 되어 있다.
- 특정 스터디 멤버 조회 시 findById()로 되어 있다.
**TO-BE**
- 위 방식대로 구현할 경우 Session이 닫히면서 proxy를 통한 Lazy loading을 못하는 이슈가 발생
- 따라서 Lazy Loading이 발생하는 코드를 모두 FETCH JOIN으로 가져와 위와 같은 문제가 발생하지 않도록 코드를 수정했습니다.
- 스터디 채널 참가 신청 테스트 코드를 변경된 메서드명으로 모두 변경했습니다.
=> fix: Lazy loading 관련 예외로 인한 코드 수정

src/main/java/com/tenten/studybadge/common/constant/NotificationConstant.java, src/main/java/com/tenten/studybadge/common/quartz/StudyEndNotificationJob.java, src/main/java/com/tenten/studybadge/notification/domain/entitiy/Notification.java, src/main/java/com/tenten/studybadge/notification/service/NotificationSchedulerService.java, src/main/java/com/tenten/studybadge/study/channel/service/StudyChannelService.java, src/main/java/com/tenten/studybadge/type/notification/NotificationType.java, src/test/java/com/tenten/studybadge/notification/service/NotificationSchedulerServiceTest.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
- StudyChannelServiceTest에 NotificationSchedulerService mock이 없었습니다.
- Notification 엔티티의 NotifcationType 필드의 length 길이를 설정하지 않았습니다.
**TO-BE**
-  StudyChannelServiceTest에 NotificationSchedulerService mock을 추가하여 테스트 코드에 영향 없도록 했습니다.
- Notification 엔티티의 NotifcationType 필드의 length 길이를 50으로 넉넉히 뒀습니다.
- NotificationType 길이가 길어지면 저장이 안되는 오류가 존재했습니다.
- 이미 create 된 엔티티면, ALTER TABLE notification MODIFY notification_type VARCHAR(50); 으로 길이를 늘려야합니다.
- 스터디 채널 모집 마감시에 NotificationSchedulerService에 있는 스터디 종료 관련 스케줄링 메서드가 작동하도록 두었습니다.
- 현재 스터디 종료 관련 알림은 다음과 같습니다.
- 1. 스터디 채널 끝나기 하루 전 알림
- 2. 스터디 채널 끝 + 환급은 다음날 하는 것 알림
- 현재는 스터디 채널 모집을 마감하는 순간 2분 후로 설정되어있어 api 테스트하기 좋으나 재설정 해야합니다.
- 현재 이 알림은 mishire를 이전의 알림과 달리 놓친 trigger가 존재하면 바로 보내도록 하였습니다.
***TODO:// 알림 시간을 정확히 언제 줄 지 팀원들과 상의 후 다시 재설정해야함*** …
=> feat: STD-20 알림 기능: 스터디 채널의 종료 전날/ 스터디 채널의 종료 날 스터디 멤버들에게 알림 전송

src/main/java/com/tenten/studybadge/common/constant/NotificationConstant.java, src/main/java/com/tenten/studybadge/common/quartz/RepeatScheduleNotificationJob.java, src/main/java/com/tenten/studybadge/common/quartz/SingleScheduleNotificationJob.java, src/main/java/com/tenten/studybadge/notification/service/NotificationSchedulerService.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java
**AS-IS**
- relatedUrl: 프론트 url이 아닌 백엔드의 api url을 임시로 두었음
- 일정 관련 message 형식: study channel의 id 명시
- 일정 관련 message 형식 중 date format 형식 2024년 7월 27일
- 일정 관련 알림 전송하는 메서드 2개(생성, 수정/삭제)
**TO-BE**
- relatedUrl: /channel/1/schedule/2024-07-27 (프론트 url)
- 일정 관련 message 형식 변경: study channel의 name 명시로 변경(사용자의 편의를 위해)
- 일정 관련 message 형식 변경: date format 형식 2024-07-27 으로 변경(format 1개 사용을 위해)
- 일정 관련 알림 전송하는 메서드 1개로 수정(relatedUrl이 1개이기 때문에)
=> refactor: STD-20 일정 관련 알림 전송하는 relatedUrl 형식 변경 및 jobDataMap에 formattedDate도 같이 저장 후 전달

src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java, src/main/java/com/tenten/studybadge/study/channel/service/StudyChannelService.java, src/main/java/com/tenten/studybadge/study/member/domain/repository/StudyMemberRepository.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
**TO-BE**
- 프론트에서 스터디 채널 카드 메뉴 탭 활성화에 필요한 해당 로그인 유저가 스터디 채널의 스터디 멤버인지 확인하는 api를 추가했습니다.
=> feat: STD-45 스터디 채널의 스터디 멤버인지 확인하는 기능

src/main/java/com/tenten/studybadge/member/dto/MemberResponse.java
**AS-IS**
- memberResponse에 id가 존재하지 않았습니다.
**TO-BE**
- memberResponse에 memberId를 클라이언트가 저장할 수 있도록 추가했습니다.
=> refactor: STD-4 회원 정보 조회시 member id도 return 하도록 수정

src/main/java/com/tenten/studybadge/common/config/SchedulingConfig.java, src/main/java/com/tenten/studybadge/notification/domain/entitiy/Notification.java, src/main/java/com/tenten/studybadge/notification/domain/repository/NotificationRepository.java, src/main/java/com/tenten/studybadge/notification/service/NotificationCleanerService.java
**AS-IS**
- 일정에 인덱스를 두지 않았습니다.
**TO-BE**
- createAt에 인덱스 설정했습니다.
- 현재 날짜보다 30일 지난 알림들 새벽 3시에 벌크 삭제 스케줄 등록
- batch size 단위로 삭제하고 있습니다. 
- 벌크 연산이라 repository단에 트랜잭션을 걸었으며 매일 3시에 반복되는 일정이므로 서비스단으로 트랜잭션을 걸진 않았습니다.
***현재 batch size로 삭제하는 패턴과 batch size 없이 삭제하는 패턴을 SpringbootTest로 테스트 진행 중에 있으나 설정 문제로 시간이 걸릴 것 같아 먼저 pr 올렸습니다.***
=> refactor: STD-20 일정; 오늘 날짜로 30일 지난 일정들은 벌크 연산으로 삭제

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/MailConstant.java, src/main/java/com/tenten/studybadge/member/dto/MemberStudyList.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java, src/main/java/com/tenten/studybadge/participation/domain/repository/ParticipationRepository.java
**AS-IS**
- 이메일 인증 링크가 서버 주소로 되어있었습니다.
- my-study api주소가 security에 포함되지 않았었습니다.
- 기존 findByMemberId로 참가자나 스터디원을 찾아왔었습니다.
**TO-BE**
- 배포 후 인증 링크 주소를 프론트 측과 상의하여 변경하였습니다.
- 회원 스터디 목록 조회에 출석률을 추가하였습니다.
- my-study api주소를 security에 추가하였습니다.
- 민호님 말씀대로, findByMemberId -> findAllByMemberIdWithStudyChannel(Long memberId) 로 변경하였습니다.
=> refactor: STD-4 회원 스터디 조회 수정

src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/study/channel/service/StudyChannelService.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java, src/test/java/com/tenten/studybadge/study/channel/service/StudyChannelServiceTest.java
**AS-IS**
- 포인트 내역에 차감 된 금액을 + 값으로 넣은 형태이다.
**TO-BE**
- 스터디 채널 생성시 등록한 예치금의 금액보다 적은 포인트를 보유하고 있을 경우 스터디 채널을 생성하지 못하도록 했습니다.
- 스터디 채널 생성 시 예치금 등록과정과 포인트 내역, 회원의 포인트 차감이 되도록 기능을 추가했습니다.
=> feat: 스터디 생성시 포인트 및 예치금 관련 기능 추가 

src/main/java/com/tenten/studybadge/notification/controller/NotificationController.java, src/main/java/com/tenten/studybadge/notification/domain/entitiy/Notification.java, src/main/java/com/tenten/studybadge/notification/domain/repository/NotificationRepository.java, src/main/java/com/tenten/studybadge/notification/dto/NotificationResponse.java, src/main/java/com/tenten/studybadge/notification/service/NotificationSchedulerService.java, src/main/java/com/tenten/studybadge/notification/service/NotificationService.java, src/test/java/com/tenten/studybadge/notification/controller/NotificationControllerTest.java, src/test/java/com/tenten/studybadge/notification/service/NotificationServiceTest.java
**AS-IS**
- 이전에는 알림 전체 조회, 안읽은 알림 전체 조회시 List로 반환했습니다.
**TO-BE**
- 프론트와 상의해 page로 반환하여 최신순으로 알림이 정렬된 채로 주는 것으로 수정했습니다.
- controller 테스트 코드는 현재  IllegalStateException: argument type mismatch 에러가 나는 상황 입니다.
- memberId 와 pageable 두개의 매개변수가 필요한데 둘다 value = 1로 들어온다는 에러
- 시간이 너무 빠듯해 임시 방편으로 주석처리
=> refactor: STD-40, STD-42 알림 전체 반환 시 List -> Page로 수정

src/main/java/com/tenten/studybadge/attendance/service/AttendanceService.java, src/main/java/com/tenten/studybadge/common/utils/PagingUtils.java, src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java, src/main/java/com/tenten/studybadge/type/study/channel/SortOrder.java
**AS-IS**
- 출석 현황을 통해 출석률을 보여줄 때 일정이 등록되어 있지 않을 경우 NaN으로 반환
- 조회순으로 조회 시 POPULAR를 기준으로 둠.
- 일정 조회 시 회원 조회할 때 파라미터 순서가 studyChannelId, memberId 순
**TO-BE**
- 일정이 등록되어 있지 않을 경우 출석률을 0으로 반환하도록 수정
- 조회순을 VIEW_COUNT로 변경 
- 일정 조회 시 회원 조회할 때 파라미터 순서를 memberId, studyChannelId 순으로 변경
=> fix: 출석 현황 및 목록 조회시 정렬 문자 변경

src/main/java/com/tenten/studybadge/notification/controller/NotificationController.java, src/test/java/com/tenten/studybadge/notification/controller/NotificationControllerTest.java
**AS-IS**
- 이전에는 page의 첫번째값은 0이었습니다.
**TO-BE**
- 클라이언트/백 사이의 동일한 page 관리를 위해 첫번째 page값을 1로 받을 수 있도록 변경하였습니다.
- 이전에 page 관련 controller 테스트 코드를 주석처리했음에도 주석이 안되어있어서 다시 재설정했습니다.
=> refactor: STD-40, STD-42 알림 page 요청시 기본 첫번째 값을 0에서 1로 변경

src/main/java/com/tenten/studybadge/common/constant/MailConstant.java, src/main/java/com/tenten/studybadge/common/email/MailService.java, src/main/java/com/tenten/studybadge/common/oauth2/OAuth2UserInfo.java
**AS-IS**
- oauth2 가입 시 isPasswordAuth가 null로 저장됐습니다.
**TO-BE**
-  oauth2 가입 시 isPasswordAuth가 기본 false로 저장되게 하였습니다.  
( 사실 Oauth2 유저에겐 필요없지만 null값이 불편해서 수정합니다. )
- 비밀번호 변경 메일 폼을 자연스럽게 변경하였습니다.
=> style: oauth2 가입 시 필드 추가

src/main/java/com/tenten/studybadge/attendance/service/AttendanceService.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannel.java, src/main/java/com/tenten/studybadge/study/member/domain/repository/StudyMemberRepository.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java
**AS-IS**
- 스터디 멤버 조회 시 현재 참여중인 멤버를 제외한 나간 멤버, 밴당한 멤버 모두 조회하는 형태
- 스터디 채널 내 정원이 가득찼는지 판단하는 로직이 모든 스터디 멤버를 조회했을 때의 수로 비교
**TO-BE**
- 스터디 멤버 조회 시 현재 참여중인 멤버만 조회하도록 수정
- 스터디 채널 내 정원이 가득찼는지 판단을 현재 참여중인 멤버를  통해 비교하도록 수정
=> feat: 회원 상태에 따른 로직 변경

src/main/java/com/tenten/studybadge/common/exception/studychannel/EndStudyChannelException.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java
**AS-IS**
- 오늘 날짜를 기준으로 조회를 분기처리
**TO-BE**
- 위 처럼 구현할 경우 당일에 출석 체크를 진행했는데 출석 체크 되지 않은 형태의 조회 결과가 나오는 문제를 해결
- 참가 신청시 종료된 스터디일 경우 참가 신청을 불가하도록 추가
=> feat: 잘못된 스터디 멤버 조회 방식 및 종료된 스터디 참가 불가 기능 추가

src/main/java/com/tenten/studybadge/common/exception/member/ExistPointException.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java
**AS-IS**
- 회원 탈퇴 시 포인트가 있어도 탈퇴가 진행되었습니다.
- 회원 탈퇴 시 refreshToken을 삭제 하지 않았었습니다.
**TO-BE**
- 회원 탈퇴 시 포인트가 있으면 탈퇴가 진행되지 않도록 수정했습니다.
- 회원 탈퇴 시 refreshToken을 삭제하도록 수정하였습니다.
=> refactor: STD-4 회원탈퇴 수정
