src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/exception/schedule/IllegalArgumentForRepeatSituationException.java, src/main/java/com/tenten/studybadge/common/exception/schedule/IllegalArgumentForScheduleRequestException.java, src/main/java/com/tenten/studybadge/common/jsondeserializer/RepeatSituationNumberDeserializer.java, src/main/java/com/tenten/studybadge/schedule/controller/ScheduleController.java, src/main/java/com/tenten/studybadge/schedule/domain/Schedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/RepeatSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/SingleSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/RepeatScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/ScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/SingleScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/dto/RepeatScheduleCreateRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/ScheduleCreateRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/ScheduleResponse.java, src/main/java/com/tenten/studybadge/schedule/dto/SingleScheduleCreateRequest.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/main/java/com/tenten/studybadge/type/schedule/RepeatCycle.java, src/main/java/com/tenten/studybadge/type/schedule/RepeatSituation.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
**TO-BE**
- type: single or repeat에 따라 단일 일정 / 반복 일정 등록
-  단일 일정 등록
```
{
"type": "single",
"scheduleName": "One-time Meeting",
"scheduleContent": "Discussion on project progress and planning",
"scheduleDate": "2024-07-05",
"scheduleStartTime": "10:00:00",
"scheduleEndTime": "11:00:00",
"placeId": 1
} 
```
- 반복 일정 등록
```
{
"type": "repeat",
"scheduleName": "Weekly Team Meeting",
"scheduleContent": "Discussion on project progress and planning",
"scheduleDate": "2024-07-05",
"scheduleStartTime": "10:00:00",
"scheduleEndTime": "11:00:00",
"repeatCycle": "WEEKLY",
"repeatSituation": "월요일",
"repeatEndDate": "2024-12-31"
}
{
"type": "repeat",
"scheduleName": "Monthly Team Meeting",
"scheduleContent": "Discussion on project progress and planning",
"scheduleDate": "2024-07-15", …
```
=> feat: STD-16 일정 등록

src/main/java/com/tenten/studybadge/participation/controller/StudyChannelParticipationController.java, src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java
**AS-IS**
* 스터디 채널, 채널 참가 신청 Controller에 문서화를 위한 작업 X
**TO-BE**
* 문서화를 위해 스터디 채널, 채널 참가 신청 Controller에 Swagger 적용
=> feat: 스터디 채널 Swagger 적용

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/TokenConstant.java, src/main/java/com/tenten/studybadge/common/exception/participation/InvalidApprovalStatusException.java, src/main/java/com/tenten/studybadge/common/exception/participation/NotAuthorizedApprovalException.java, src/main/java/com/tenten/studybadge/common/exception/participation/OtherStudyChannelParticipationException.java, src/main/java/com/tenten/studybadge/common/jwt/JwtTokenCreator.java, src/main/java/com/tenten/studybadge/common/token/controller/TokenController.java, src/main/java/com/tenten/studybadge/common/token/service/TokenService.java, src/main/java/com/tenten/studybadge/common/utils/CookieUtils.java, src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/participation/controller/StudyChannelParticipationController.java, src/main/java/com/tenten/studybadge/participation/domain/entity/Participation.java, src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/schedule/controller/ScheduleController.java, src/main/java/com/tenten/studybadge/schedule/domain/Schedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/RepeatSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/SingleSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/RepeatScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/ScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/domain/repository/SingleScheduleRepository.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/main/java/com/tenten/studybadge/study/channel/domain/entity/StudyChannel.java, src/main/java/com/tenten/studybadge/study/member/domain/entity/StudyMember.java, src/test/java/com/tenten/studybadge/participation/service/StudyChannelParticipationServiceTest.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
**TO-BE**
* 스터디 리더가 참가 신청을 승인하는 기능
* 승인할 때 아래 조건을 만족하지 못하면 예외를 발생시킵니다.
*  만약 다른 스터디 채널의 참가 신청을 승인하려고 할 경우 예외가 발생합니다.
* 해당 스터디 채널의 리더가 아닌데 승인하려고 할 경우 예외가 발생합니다.
* 참가 신청 상태가 승인 대기중이 아닌 경우에는 예외가 발생합니다.
참가 신청을 승인할 경우 **참가 신청의 상태는 APPROVED**(승인됨) 이 되고 
해당 **스터디 채널의 스터디 멤버**로 저장됩니다.
- 컨트롤러 테스트의 경우 추후 추가할 예정입니다.
=> feat: STD-14 스터디 채널 참가 신청 승인 기능

src/main/java/com/tenten/studybadge/common/security/CustomUserDetails.java, src/main/java/com/tenten/studybadge/common/token/controller/TokenController.java, src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/member/dto/MemberResponse.java, src/main/java/com/tenten/studybadge/member/dto/MemberUpdateRequest.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java
**AS-IS**
- TokenController에 불필요한 import 삭제
**TO-BE**
- 회원 정보 ( 내 정보 ) 조회
- 회원 정보 수정
-  이미지 업로드(AWS S3) 추가
=> Feat: STD-4 회원 정보 조회, 수정

src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java
**AS-IS**
- 기존 findByEmailAndPlatform -> findById 로 수정하고, 그와 관련된 코드도 함께 수정했습니다.
**TO-BE**
- 회원 탈퇴 기능 추가
- 탈퇴 시 ACTIVE -> WITHDRAWN 상태 변경
=> Feat: STD-4 회원 탈퇴 추가 + findBy 수정

src/main/java/com/tenten/studybadge/common/config/CorsConfig.java, src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/controller/HealthCheckController.java, src/test/java/com/tenten/studybadge/global/cors/CorsTest.java
**AS-IS**
**TO-BE**
- health-check할 controller 생성
- securityConfig에 `/health-check` permitAll에 설정
- application.yml에 frontend.domain 값 설정
- SpringBootTest로  테스트를 진행했습니다.
``` java
@Test
@DisplayName("Preflight request")
void testPreflightRequest() throws Exception {
mockMvc.perform(options("/health-check")
.header("Origin", "https://study-badge.vercel.app")
.header("Access-Control-Request-Method", "GET"))
.andExpect(status().isOk())
.andExpect(header().string("Access-Control-Allow-Origin", "https://study-badge.vercel.app"))
.andExpect(header().string("Access-Control-Allow-Methods", "GET,POST,PUT,PATCH,DELETE"))
.andExpect(header().string("Access-Control-Allow-Credentials", "true"));
}
```
=> feat: 프론트와 연동을 위한 중간 배포 (ec2 https)

src/main/java/com/tenten/studybadge/common/exception/schedule/IllegalArgumentForScheduleEditRequestException.java, src/main/java/com/tenten/studybadge/common/exception/schedule/InvalidScheduleModificationException.java, src/main/java/com/tenten/studybadge/common/jsondeserializer/ScheduleEditRequestDeserializer.java, src/main/java/com/tenten/studybadge/common/jsondeserializer/ScheduleTypeDeserializer.java, src/main/java/com/tenten/studybadge/schedule/controller/ScheduleController.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/RepeatSchedule.java, src/main/java/com/tenten/studybadge/schedule/domain/entity/SingleSchedule.java, src/main/java/com/tenten/studybadge/schedule/dto/RepeatScheduleEditRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/ScheduleEditRequest.java, src/main/java/com/tenten/studybadge/schedule/dto/SingleScheduleEditRequest.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java, src/main/java/com/tenten/studybadge/type/schedule/ScheduleType.java, src/test/java/com/tenten/studybadge/schedule/service/ScheduleServiceTest.java
**AS-IS**
- scheduleEditReqeust를 추상 클래스로 두고 single/ repeat는 상속 받아서 구현했으며 **type** 필드로 구분되어 json 역직렬화를 이용했음.
- 서비스 로직 내에 repeat, single을 생성할때 builder 패턴을 그대로 사용했음.
- 날짜를 비교할 때 equals 메서드 사용.
-  기존 수정 시 제한 사항
- 수정할 때 기존 반복 일정의 반복 주기와 다르면 제한
- 반복 일정으로 수정시 입력한 scheduleDate가 입력한 요일/ 입력한 일자와 맞는지 매칭 후 틀리면 exception
- 수정 request 예시
```json
{
"scheduleId" : 1,
"scheduleName": "단일 일정-> 단일 일정 수정",
"scheduleContent": "수~정",
"originType" : "single",
"type" : "single",
"selectedDate": "2024-07-05",
"scheduleStartTime": "22:00:00",
"scheduleEndTime": "23:00:00",
"placeId": null
}
```
**TO-BE**
- scheduleEditReqeust를 추상 클래스로 둔 것 삭제
- scheduleeditReqeust를 인터페이스로 만들고 **editType**을 역직렬화로 구분하여 단일 일정/ 반복 일정으로 변경 요청
- 기존 ScheduleOriginType -> ScheduleType으로 변경해 재사용성을 높임
- 반복 일정 -> 단일 일정으로 수정할 때는 request 값을 …
=> refactor: STD-18 일정 수정

src/main/java/com/tenten/studybadge/common/exception/schedule/CanNotDeleteForBeforeDateException.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java
**AS-IS**
- 날짜 제한 없이 삭제 가능
**TO-BE**
- 현재 날짜로 지난 일정일 경우 삭제 불가
=> refactor: STD-19 일정 삭제 시 지난 일정은 삭제 불가로 제한

src/main/java/com/tenten/studybadge/payment/controller/PaymentController.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentFail.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentFailRequest.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java, src/main/java/com/tenten/studybadge/schedule/service/ScheduleService.java
**AS-IS**
빌드 시 Notification 오류가 나타났었습니다. 
**TO-BE**
- 결제 실패 기능을 추가하였습니다.
- 로컬 테스트 시 결제할 때 잔액이 없어도 결제가 되어, 잔액 부족 등
결제 실패할 상황이 없어, 일단 postman으로 API 테스트 완료했습니다.
- 빌드 시 Notification 오류가 나타나 일단 한슬님 요구대로 주석처리 해놓았습니다.
=> Feat: STD-9 결제 실패 기능 구현

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/constant/Oauth2Contant.java, src/main/java/com/tenten/studybadge/common/exception/point/NotFoundPointException.java, src/main/java/com/tenten/studybadge/common/oauth2/OAuth2SuccessHandler.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentHistory.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java, src/main/java/com/tenten/studybadge/point/controller/PointController.java, src/main/java/com/tenten/studybadge/point/domain/entity/Point.java, src/main/java/com/tenten/studybadge/point/domain/repository/PointRepository.java, src/main/java/com/tenten/studybadge/point/domain/service/PointService.java, src/main/java/com/tenten/studybadge/point/dto/PointResponse.java, src/main/java/com/tenten/studybadge/type/point/PointHistoryType.java, src/main/java/com/tenten/studybadge/type/point/TransferType.java
**AS-IS**
Oauth2SuccessHandler에서 토큰이 헤더에 잘 전달 되지 않았었습니다.
REDIRECT_URL이 Token 컨트롤러를 향하고 있었습니다.
**TO-BE**
- 포인트 테이블을 추가하였습니다.
- 기능으로는 사용자의 포인트 변경내역 조회 기능이 있습니다.
- Oauth2SuccessHandler에서 토큰이 헤더에 잘 전달 되도록 수정하였습니다.
- REDIRECT_URL을 프론트 상의하여 임시로 수정하였습니다. ( 현재 기능 확인 중으로 변경될 수 있습니다. )
=> feat: STD-34 포인트 기능 추가

src/main/java/com/tenten/studybadge/common/exception/notification/NotificationNotFoundException.java, src/main/java/com/tenten/studybadge/notification/controller/NotificationController.java, src/main/java/com/tenten/studybadge/notification/domain/entitiy/Notification.java, src/main/java/com/tenten/studybadge/notification/domain/repository/NotificationRepository.java, src/main/java/com/tenten/studybadge/notification/dto/NotificationReadRequest.java, src/main/java/com/tenten/studybadge/notification/service/NotificationService.java, src/test/java/com/tenten/studybadge/notification/controller/NotificationControllerTest.java, src/test/java/com/tenten/studybadge/notification/service/NotificationServiceTest.java
**AS-IS**
**TO-BE**
- 특정 사용자의 특정 알림 읽음 처리
- Notification의 isRead 필드를 Setter 어노테이션을 두어 변경하도록 하였습니다.
=> feat: STD-41 알림 읽음 처리

src/main/java/com/tenten/studybadge/notification/controller/NotificationController.java, src/main/java/com/tenten/studybadge/notification/domain/repository/NotificationRepository.java, src/main/java/com/tenten/studybadge/notification/service/NotificationService.java, src/test/java/com/tenten/studybadge/notification/controller/NotificationControllerTest.java, src/test/java/com/tenten/studybadge/notification/service/NotificationServiceTest.java
**AS-IS**
**TO-BE**
- 특정 사용자에 해당되는 알림 중 안읽은 알림 전체 조회
=> feat: STD-42 안읽은 알림 전체 조회

src/main/java/com/tenten/studybadge/payment/domain/entity/Payment.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentConfirmRequest.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentHistory.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentRequest.java, src/main/java/com/tenten/studybadge/payment/dto/PaymentResponse.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java, src/main/java/com/tenten/studybadge/point/domain/entity/Point.java
**AS-IS**
금액 관련 데이터 타입이 Long, Integer로 섞여있었습니다.
**TO-BE**
금액 관련 데이터 타입을 Integer로 통합하였습니다.
=> refactor: STD-5 금액 관련 타입 변경

src/main/java/com/tenten/studybadge/point/dto/PointResponse.java, src/test/java/com/tenten/studybadge/payment/service/PaymentServiceTest.java
**AS-IS**
- 미처 변경 못한 타입이 있었습니다.
**TO-BE**
- Long -> Integer로 변경하였습니다.
- 그에맞게 테스트 코드도 Integer에 맞게 변경하였습니다.
=> style: STD-5 Test 코드 수정

src/main/java/com/tenten/studybadge/participation/service/StudyChannelParticipationService.java, src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java
**AS-IS**
- Long -> Integer, Integer -> Long으로 변환하는 코드 존재
**TO-BE**
- Integer로 통합됨에 따라 연산 부분 코드 수정
=> refactor: 금액 데이터 타입 변경에 따른 코드 수정

src/main/java/com/tenten/studybadge/common/exception/basic/GlobalExceptionHandler.java
**AS-IS**
- 요청 body값이 잘못된 상황에서 MethodArgumentNotValidException가 아닌 org.springframework.security.access.AccessDeniedException로 에러 로그가 찍히고 포스트맨에서는 400에러로만 떠서 문제 상황을 파악하기 어려웠습니다.
```
2024-07-24T20:10:32.996+09:00 ERROR 27764 --- [study_badge] [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Unable to handle the Spring Security Exception because the response is already committed.] with root cause
org.springframework.security.access.AccessDeniedException: Access Denied
at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:98) ~[spring-security-web-6.3.1.jar:6.3.1]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilt …
```
=> refactor: global handler에 여러 exception class 잡는 것을 추가

src/main/java/com/tenten/studybadge/attendance/domain/repository/AttendanceRepository.java, src/main/java/com/tenten/studybadge/attendance/service/AttendanceService.java, src/main/java/com/tenten/studybadge/study/member/domain/repository/StudyMemberRepository.java
**AS-IS**
**TO-BE**
- 추후에 내 스터디 목록 조회 기능에 출석률을 추가할 수 있도록 스터디 멤버의 출석률을 계산할 수 있도록 코드를 구현했습니다.
=> feat: STD-36 특정 스터디 멤버의 출석률 계산 기능 구현

.github/workflows/github-actions.yml
**AS-IS**
**TO-BE**
- 깃허브 액션 테스트
=> test: CI테스트

.github/workflows/github-actions.yml
=> test: CI 테스트3

.github/workflows/github-actions.yml
=> test: CI 테스트4

.github/workflows/github-actions.yml
=> test: CI 테스트5

appspec.yml, buildspec.yml, scripts/deploy.sh, scripts/healthCheck.sh
**AS-IS**
**TO-BE**
- appspec, buildspec 추가
- 스크립트 추가
=> test: CI/CD 테스트6

.github/workflows/github-actions.yml
**AS-IS**
**TO-BE**
- CICD 테스트8
=> test: CICD 테스트 8

scripts/healthCheck.sh
=> test: CI/CD 테스트 9

.github/workflows/github-actions.yml
**AS-IS**
**TO-BE**
- CICD 테스트 11
=> feat: CICD 테스트 11

.github/workflows/github-actions.yml
**AS-IS**
**TO-BE**
-CICD 테스트 12
=> test: CICD 12

.github/workflows/github-actions.yml
**AS-IS**
**TO-BE**
-CICD 테스트 13
=> test: CICD 테스트 13

.github/workflows/github-actions.yml
**AS-IS**
**TO-BE**
- CICD 테스트 14
=> test: CICD 테스트 14

.github/workflows/github-actions.yml
**AS-IS**
- depoly, deploy-group 의 이름과 bucket 을 secret에 넣지 않았었습니다.
**TO-BE**
- Github Actions + S3 + Code Deploy : CI/CD  구축 완료했습니다.
- 현재 PR에는 변경내역이 반영안되어 있으며, 테스트 PR에 추가/변경내역이 있는 점 이해부탁드립니다.
- 10번의 테스트 과정을 거쳐,  develop로 push 시  빌드, 테스트 및 배포 단계를 자동화하였습니다.
- 현재는 develop지만, 추후 main으로 변경할 예정입니다.
- application.yml 은 actions secret에 Base64로 인코딩하여 저장한 후, 빌드 전에 디코딩하여 내용을 넣어주고 있습니다.
- secret에 application 속성 값을 넣어주는 방법도 있긴 하지만, 일단 위의 방식으로 진행하였습니다.
- depoly, deploy-group 의 이름과 bucket 을 secret에 넣어 관리하게하였습니다.
=> feat: STD-44 CI/CD 구축

build.gradle, scripts/deploy.sh
=> hotfix: STD-44 cicd

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/email/MailService.java, src/main/java/com/tenten/studybadge/common/utils/CookieUtils.java, src/main/java/com/tenten/studybadge/member/controller/MemberController.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java
**AS-IS**
**TO-BE**
- 회원가입 인증 코드 재발송 기능을 추가했습니다.
- signUp 메서드 리팩토링
- 쿠키 도메인 변경 ( cross 테스트 :  sameStie=None :: Secure 와 같이 Secure 를 같이 사용하면 보안이 강화되지만, 
안전하다고 볼 순 없습니다. 하지만,  다른 도메인에서 쿠키를 공유할 수 있기는 합니다. 
일단 현재는 테스트로 진행중입니다.)
=> refactor: STD-4 회원가입 리팩토링, 코드 재발송 추가

.github/workflows/github-actions.yml
=> refactor: main 브랜치로 푸시될 때 동작하도록 변경

src/main/java/com/tenten/studybadge/study/channel/domain/repository/StudyChannelRepository.java, src/main/java/com/tenten/studybadge/study/channel/dto/StudyChannelDetailsResponse.java, src/main/java/com/tenten/studybadge/study/channel/service/StudyChannelService.java
**AS-IS**
**TO-BE**
- 특정 스터디 채널 조회 시 조회수를 증가시키는 기능을 추가
- 특정 스터디 채널 조회 시 조회수도 보일 수 있도록 응답값에 조회수 추가
=> feat: 특정 스터디 채널 조회 수 조회수 증가 기능 추가

src/main/java/com/tenten/studybadge/member/dto/MemberResponse.java, src/main/java/com/tenten/studybadge/payment/service/PaymentService.java
**AS-IS**
- MemberResponse에 accountBank 필드가 빠졌었습니다.
**TO-BE**
- OIV = false 로 변경 후 JPA오류가 나타나 requestPayment 메서드에 Transactioanl을 적용하였습니다.
- MemberResponse에 accountBank 필드를 추가했습니다.
=> chore: STD-5 결제 관련 수정

src/main/java/com/tenten/studybadge/study/channel/controller/StudyChannelController.java
**AS-IS**
- 정렬 파라미터 : sort
**TO-BE**
- 정렬 파라미터를 order로 변경.
=> fix : 스터디 채널 목록 조회 시 정렬 파라미터 명 변경

src/main/java/com/tenten/studybadge/common/config/SecurityConfig.java, src/main/java/com/tenten/studybadge/common/exception/member/NotFoundMyStudyException.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java
**AS-IS**
- exception이 NotFoundMember로 적절하지않았습니다.
- withdrawal이 security에 포함되어 있지 않았습니다.
**TO-BE**
- exception을 상황에 적절하게  NotFoundMyStudy로 변경하였습니다.
- withdrawal을 security에 추가하였습니다.
=> style: STD-4 예외 수정

src/main/java/com/tenten/studybadge/notification/controller/NotificationController.java, src/main/java/com/tenten/studybadge/notification/service/NotificationService.java
**AS-IS**
- 타임아웃 2분
**TO-BE**
- 타임아웃 1시간으로 변경
- response 헤더를 명시적으로 설정(X-Accel-Buffering)
=> fix: nginx가 앞단에 있을 때 sse 설정 변경

src/main/java/com/tenten/studybadge/common/constant/MailConstant.java
**AS-IS**
- ">" 가 빠져서 인증코드가 오지않았습니다.
**TO-BE**
- ">"를 추가하였습니다.
=> style: STD-4 이메일 폼 수정

src/main/java/com/tenten/studybadge/study/member/domain/entity/StudyMember.java, src/main/java/com/tenten/studybadge/study/member/dto/StudyMemberInfoResponse.java
**AS-IS**
**TO-BE**
- 스터디 멤버 조회 시 스터디 멤버 ID를 추가했습니다.
=> feat: 스터디 멤버 조회 시 스터디 멤버 식별자 추가

src/main/java/com/tenten/studybadge/study/member/service/StudyMemberService.java
**AS-IS**
- 기존에는 서브 리더가 있을 경우 바로 예외 처리.
**TO-BE**
- 서브리더가 존재할 경우 해당 서브 리더의 권한을 스터디 멤버로 변경하고 새로운 스터디 멤버에 서브리더 권한 부여하는 형태로 변경
=> fix: 서브 리더 부여 기능 변경

src/main/java/com/tenten/studybadge/common/exception/member/ExistPointException.java, src/main/java/com/tenten/studybadge/member/service/MemberService.java
**AS-IS**
- 회원 탈퇴 시 포인트가 있어도 탈퇴가 진행되었습니다.
- 회원 탈퇴 시 refreshToken을 삭제 하지 않았었습니다.
**TO-BE**
- 회원 탈퇴 시 포인트가 있으면 탈퇴가 진행되지 않도록 수정했습니다.
- 회원 탈퇴 시 refreshToken을 삭제하도록 수정하였습니다.
=> refactor STD-4 withdrawal
